name: Deploy to iPage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Install lftp
      run: sudo apt-get install -y lftp
    
    - name: Deploy with lftp
      env:
        FTP_USERNAME: ${{ secrets.IPAGE_FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.IPAGE_FTP_PASSWORD }}
      run: |
        # Create .netrc file for authentication
        echo "machine ftp.theprojectx.co
        login $FTP_USERNAME
        password $FTP_PASSWORD" > ~/.netrc
        chmod 600 ~/.netrc
        
        # Set up lftp configuration
        echo "set ssl:verify-certificate no
        set ftp:ssl-allow no
        set ftp:ssl-force no
        set ftp:ssl-protect-data no
        set ftp:passive-mode on
        set ftp:prefer-epsv off" > ~/.lftprc
        
        # Deploy using lftp with explicit settings
        lftp -c "
        open ftp://ftp.theprojectx.co:21;
        set net:timeout 10;
        set net:max-retries 3;
        set net:reconnect-interval-base 5;
        mirror --reverse --delete --verbose ./out/ /
        "