name: Deploy to iPage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to iPage via FTP
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ftp.theprojectx.co
        ftp_username: ${{ secrets.IPAGE_FTP_USERNAME }}
        ftp_password: ${{ secrets.IPAGE_FTP_PASSWORD }}
        local_source_dir: ./out
        dist_target_dir: /
        delete: true
        exclude: "'^.git/'"