name: Deploy to iPage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to iPage via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: ${{ secrets.IPAGE_FTP_USERNAME }}
        server: ftp.theprojectx.co
        port: 22  # Standard SFTP port
        local_path: ./out/*
        remote_path: /
        password: ${{ secrets.IPAGE_FTP_PASSWORD }}
        sftpArgs: '-o StrictHostKeyChecking=no'