name: Deploy to iPage

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build
      run: npm run build
    
    - name: Deploy to iPage
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp.theprojectx.co
        username: ${{ secrets.IPAGE_FTP_USERNAME }}
        password: ${{ secrets.IPAGE_FTP_PASSWORD }}
        local-dir: ./out/
        dangerous-clean-slate: true
        server-dir: /
        protocol: ftps
        security: loose